### ISSUE TITLE
Contribution-Documentation

### ISSUE THREAD

**Issue by SKoschnicke** [denibertovic/docker-hs#37]
I would like to add a guide how to setup the development environment for contributing to the project in `CONTRIBUTING.md` (which is a stub currently). Is a pull request for that welcome? Any pointers to already existing documentation?

**Comment by jprider63** [comment]
There is some text in the `Contributing` section of `README.md`. @denibertovic, should we keep this where it is and link to it in `CONTRIBUTING.md`, or move this text into `CONTRIBUTING.md`? 

Maybe it makes sense to add a `Development environment` section to `README.md`. This probably would involve links to install docker and how to run the tests (something like `RUN_INTEGRATION_TESTS=1 stack test`).

**Comment by SKoschnicke** [comment]
Okay, I will put something together tomorrow (central european time)! I think there should be some text directly in `CONTRIBUTING.md` because GitHub links to that file in notification texts.

**Comment by denibertovic** [comment]
@SKoschnicke @jprider63 I agree that it's useful to add this stuff into CONTRIBUTING.md because then it will get linked on each new issue/pr creation...which is nice. So 👍 

I'm not sure as to the content of that file...Currently it's just the stuff we have already in the readme...unless we wanna come up with more process. But.....I'm not sure we need too much process at this time.

As for adding development environment docs I think that should go into the README.md file yes.
Feel free to add that. If you don't end up adding it I will probably get to it tomorrow.

**Comment by SKoschnicke** [comment]
Added a PR, open for discussion :-)
